# Generated by Django 4.2.23 on 2025-07-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='confirm_password',
            field=models.CharField(default=123456, max_length=16),
            preserve_default=False,
        ),
    ]
