# Generated by Django 4.2.23 on 2025-07-31 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapi', '0002_studentmodel_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='confirm_password',
        ),
    ]
