version: '3.9'

services:
  web:
    build: .
    command: gunicorn docker_django_postgresql_swagger.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/docker_dir
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: docker_db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imrandell
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: