version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/Kubernet_ex
    ports:
      - "8005:8005"
   

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # access on http://localhost/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web