version: '3.9'

services:
  web:
    build: .
    command: gunicorn FBV.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: imrandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imrandell
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
