version: '3.9'

services:
  web:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/FBV_crud 
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DJANGO_SETTINGS_MODULE=FBV_crud.settings
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql-container123
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: imran123
      MYSQL_DATABASE: django_fbv
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    

volumes:
  mysql_data:
