version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/fullpractice
    ports:
      - "8002:8002"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fpractice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imrandell
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"   # access on http://localhost/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
volumes:
  postgres_data: